MazadMarket/Controllers/ProductsTypesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MazadMarket.Models;

namespace MazadMarket.Controllers
{
    public class ProductsTypesController : Controller
    {
        private Model1 db = new Model1();

        // GET: ProductsTypes
        public ActionResult Index()
        {
            return View(db.ProductsTypes.ToList());
        }

        public ActionResult Indexs()
        {
            return View(db.ProductsTypes.ToList());
        }

        // GET: ProductsTypes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }


            ProductsType productsType = db.ProductsTypes.Find(id);
            if (productsType == null)
            {
                return HttpNotFound();
            }
            return View(productsType);
        }

        // GET: ProductsTypes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProductsTypes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ProductsType productsType, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {

                var allowedExtensions = new[] { ".Jpg", ".png", ".PNG", ".jpg", "jpeg" };

                var fileimage = file.ToString(); //getting complete url   MHD.php.png

                var fileName = Path.GetFileName(file.FileName); //getting only file name(ex-ganesh.jpg)  
                var ext = Path.GetExtension(file.FileName); //getting the extension(ex-.jpg)  
                if (allowedExtensions.Contains(ext)) //check what type of extension  
                {
                    string name = Path.GetFileNameWithoutExtension(fileName); //getting file name without extension  
                    string myfile = name + "_" + ext; //appending the name with id  
                                                      // store the file inside ~/project folder(Img)  
                    var path = Path.Combine(Server.MapPath("~/ProductTypeImage"), myfile);

                    file.SaveAs(path);

                    productsType.Picture = myfile;
                }
                else
                {
                    ViewBag.message = "Please choose only Image file";
                }



                db.ProductsTypes.Add(productsType);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(productsType);
        }

        // GET: ProductsTypes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductsType productsType = db.ProductsTypes.Find(id);
            if (productsType == null)
            {
                return HttpNotFound();
            }
            return View(productsType);
        }

        // POST: ProductsTypes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ProductsType productsType, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {

                if (file != null)
                {
                    var allowedExtensions = new[] { ".Jpg", ".jpg", ".png", ".PNG", ".jpg", ".jpeg" };

                    var fileimage = file.ToString(); //getting complete url  

                    var fileName = Path.GetFileName(file.FileName); //getting only file name(ex-ganesh.jpg)  
                    string ext = Path.GetExtension(file.FileName).ToLower();//getting the extension(ex-.jpg)  



                    if (allowedExtensions.Contains(ext)) //check what type of extension  
                    {
                        string name = Path.GetFileNameWithoutExtension(fileName); //getting file name without extension  
                        string myfile = name + "_" + ext; //appending the name with id  
                                                          // store the file inside ~/project folder(Img)  
                        var path = Path.Combine(Server.MapPath("~/ProductTypeImage"), myfile);

                        file.SaveAs(path);

                        productsType.Picture = myfile;
                    }
                    else
                    {
                        ViewBag.message = "Please choose only Image file";
                    }


                }


                db.Entry(productsType).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(productsType);
        }

        // GET: ProductsTypes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductsType productsType = db.ProductsTypes.Find(id);
            if (productsType == null)
            {
                return HttpNotFound();
            }
            return View(productsType);
        }

        // POST: ProductsTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ProductsType productsType = db.ProductsTypes.Find(id);
            db.ProductsTypes.Remove(productsType);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MazadMarket/Views/ProductsTypes/Create.cshtml
@model MazadMarket.Models.ProductsType
@using MazadMarket.Resourses
@{
    ViewBag.Title = @Html.Raw(layout.createNew);
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br /><br /><br /><br />

<div class="container">
    <h2>@Html.Raw(layout.createNew)</h2>



    @using (Html.BeginForm("Create", "ProductsTypes", FormMethod.Post, new
    {
        enctype = "multipart/form-data"
    }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>@Html.Raw(layout.typeName)</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.typeName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.typeName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.typeName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Picture, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" name="file" />
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="@Html.Raw(layout.createNew)" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink(  layout.backToList , "Index")
    </div>


</div>

MazadMarket/Views/ProductsTypes/Delete.cshtml
@model MazadMarket.Models.ProductsType
@using MazadMarket.Resourses
@{
    ViewBag.Title = @Html.Raw(layout.delete);
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br /><br /><br /><br />
<h2>@Html.Raw(layout.delete)</h2>

<h3>@Html.Raw(layout.deleteMessage)</h3>
<div>
    <h4>@Html.Raw(layout.typeName)</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.typeName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.typeName)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="@Html.Raw(layout.delete)" class="btn btn-default" /> |
            @Html.ActionLink(layout.backToList , "Index")
        </div>
    }
</div>

MazadMarket/Views/ProductsTypes/Details.cshtml
@model MazadMarket.Models.ProductsType
@using MazadMarket.Resourses
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br /><br /><br /><br />
  <h2>@Html.Raw(layout.details)</h2>

<div>
    <h4>@Html.Raw(layout.typeName)</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.typeName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.typeName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Picture)
        </dt>

        <dd>
            <img src="~/ProductTypeImage/@Html.DisplayFor(model => model.Picture)" style="width:100px; height:100px;" />
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink(layout.details, "Edit", new { id = Model.Id }) |
    @Html.ActionLink(layout.details, "Index")
</p>

MazadMarket/Views/ProductsTypes/Edit.cshtml
@model MazadMarket.Models.ProductsType
@using MazadMarket.Resourses
@{
    ViewBag.Title = @Html.Raw(layout.edit);
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br /><br /><br /><br /><br /><br />
<h2>@Html.Raw(layout.edit)</h2>


@using (Html.BeginForm("Edit", "ProductsTypes", FormMethod.Post, new
{
    enctype = "multipart/form-data"
}))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>@Html.Raw(layout.typeName)</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.typeName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.typeName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.typeName, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Picture, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img width="200" height="200" src="~/ProductTypeImage/@Html.DisplayFor(model => model.Picture)" />
                <input type="file" name="file" />
                @Html.HiddenFor(model => model.Picture)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="@Html.Raw(layout.save)" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MazadMarket/Views/ProductsTypes/Index.cshtml
@model IEnumerable<MazadMarket.Models.ProductsType>
@using MazadMarket.Resourses
@{
    ViewBag.Title = @Html.Raw(layout.index);
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br /><br /><br /><br />
<div class="container">
    <h2>@Html.Raw(layout.index)</h2>

    <p>
        @Html.ActionLink(layout.createNew, "Create")
    </p>
    @*<div>
        @using (Html.BeginForm("Index", "products", FormMethod.Get))
        {
            <table>
                <tr>
                    <td>
                        <span><b>Search By:</b></span>
                        @Html.RadioButton("SearchBy", "ProductName", true)
                        <text> Product Name </text>
                        @Html.RadioButton("SearchBy", "pric")
                        <text> Price </text>
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.TextBox("searchValue", null, new { Class = "Form-control", palceholder = "Enter ProductName or Price " })

                    </td>
                    <td>
                        <input type="submit" value="Search" class="btn btn-success" />
                    </td>
                </tr>
            </table>
        }
    </div>*@
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.typeName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Picture)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.typeName)
                </td>

                <td>

                    <img src="~/ProductTypeImage/@item.Picture" style="width:200px; height:200px;" />

                </td>
                <td>
                    @Html.ActionLink(layout.edit, "Edit", new { id = item.Id }) |
                    @Html.ActionLink(layout.details, "Details", new { id = item.Id }) |
                    @Html.ActionLink(layout.delete, "Delete", new { id = item.Id })
                </td>
            </tr>
        }

    </table>
</div>

MazadMarket/Views/ProductsTypes/Indexs.cshtml
@model IEnumerable<MazadMarket.Models.ProductsType>
@using MazadMarket.Resourses
@{
    ViewBag.Title = "Indexs";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<section id="secondary-banner" class="dynamic-image-13">
    <!--for other images just change the class name of this section block like, class="dynamic-image-2" and add css for the changed class-->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-8 col-sm-6 col-xs-12">
                
                <h4>@Html.Raw(layout.productDetailsDescription)</h4>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6 ">
                
            </div>
        </div>
    </div>
</section>

<br /><br />
<section class="car-block-wrap padding-bottom-40">
    <div class="container">
        <div class="row">

            @foreach (var item in Model)
            {
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 margin-bottom-none">
                    <div class="flip margin-bottom-30">
                        <div class="card">
                            <div class="face front"><img class="img-responsive" style="width: 100%; height: 200px !important;" src="~/ProductTypeImage/@item.Picture" alt=""></div>
                            <div class="face back">
                                <div class='hover_title'>@item.typeName</div>
                                <a href="~/Products/categoryProduct/@item.Id"><i class="fa fa-link button_icon"></i></a> <a href="~/ProductTypeImage/@item.Picture" class="fancybox"><i class="fa fa-arrows-alt button_icon"></i></a>
                            </div>
                        </div>
                    </div>
                    <h4><a href="~/Products/categoryProduct/@item.Id">@item.typeName</a></h4>
                </div>

            }


        </div>
    </div>
</section>

<script type="text/javascript">

    $(document).ready(function () {

        $('#product').addClass('active');

    })
</script>